### ISSUE TITLE
Save to bookmark also modulation and bandwidth

### ISSUE THREAD

**Issue by jedi7** [BatchDrake/SigDigger#147] opened 2021-07-01 07:46 UTC
Actually only frequency is stored in bookmark.
But when user wants to change between bookmarked items, then must manually also set proper values for modulation and bandwidth.
Goal is to help user and set also the stored modulation and bandwidth.

**Comment by BatchDrake** [comment] 2021-07-01 07:58
Duplicate of #139

**Closed** 2021-07-01 08:05 UTC
